[package]
name = "wikiparser-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"]} 
fantoccini = "0.22.0"
rand = "0.9.2"
regex = "1.11.1"
tokio = {version = "1.47.1",features = ["full"]}
